### ISSUE TITLE
Extension stucks as it keeps looping inside the getServicesList method

### ISSUE THREAD

**Issue by lstocchi** [talamer/vscode-knative#137]
I was trying to edit a service from the extension. When applying the modification it fails for some reason.
Now my cluster situation is this one 
![image](https://user-images.githubusercontent.com/49404737/109802855-98d7a880-7c20-11eb-930b-53b9076ab087.png)

ServiceList yaml  -> https://gist.github.com/lstocchi/24793daca063813b7391f67806520b97

If i debug the extension it keeps looping because it gets inside this `if` https://github.com/talamer/vscode-knative/blob/870ed14ee871c303ffbf8c9fde8bb50d666450a9/src/servingTree/servingDataProvider.ts#L275  And i don't see anything into the tree.

**Comment by joshuawilson** [comment]
If the status is `unknown`, then it is not ready yet. So it keeps trying to fetch it. 
I do see that it would be nice to limit how long it does this and notify the user.

**Comment by joshuawilson** [comment]
@lstocchi can you reproduce this? What did you change in the Service?

**Comment by lstocchi** [comment]
I was able to replicate it with this service 
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-test
spec:
  template:
    spec:
      containers:
        - image: brushnet/node-web-app:0.1
          env:
            - name: TARGET
              value: "Go Sample v1"
```
I guess you just need a non-working image.
The status of this service is stuck to 
```
NAME                    CONFIG NAME       K8S SERVICE NAME        GENERATION   READY     REASON
helloworld-test-6fg86   helloworld-test   helloworld-test-6fg86   1            Unknown   Deploying

```
